Contoh Studi Kasus

In [ ]:
import pandas as pd
import numpy as np

**SOAL 1**

1. Identifikasi dan jelaskan tipe data apa saja yang ada pada dataframe, ada berapa kolom dan baris, serta informasi apa saja yang terkandung dalam data tersebut?

In [ ]:
df_15=pd.read_excel('DataKompi15.xlsx')

In [ ]:
df_15.shape

(25, 5)

In [ ]:
df_15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. Peserta        25 non-null     object
 1   Nama               25 non-null     object
 2   Jurusan            25 non-null     object
 3   Berat Badan (kg)   25 non-null     int64
 4   Tinggi Badan (cm)  25 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

2. Hitunglah BMI setiap siswa dengan rumus BMI=Berat badan (kg) / (Tinggi Badan (m))2

In [ ]:
df_15["Tinggi Badan (cm)"] = df_15["Tinggi Badan (cm)"] / 100

In [ ]:
df_15.rename(columns={'Tinggi Badan (cm)': 'Tinggi Badan (m)'}, inplace=True)

In [ ]:
df_15.head()

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m)
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74
2,SC61503,Devia Heraka,Kearsipan,48,1.45
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55

In [ ]:
def rumus_bmi():
  x=df_15['Berat Badan (kg)']
  y=df_15['Tinggi Badan (m)']

  BMI = x / (y**2)

  return BMI

In [ ]:
rumus_bmi()

0     22.189349
1     22.790329
2     22.829964
3     17.481790
4     19.979188
5     21.799308
6     20.761246
7     21.359915
8     19.146722
9     22.892820
10    23.040020
11    22.031726
12    17.968750
13    18.424036
14    28.906250
15    21.096191
16    22.031726
17    20.761246
18    21.208449
19    24.221453
20    23.437500
21    18.256319
22    22.656250
23    17.993080
24    22.806017
dtype: float64

3. Buatlah program untuk menghitung BMI!

In [ ]:
def bmi():
  x=int(input('Berat Badan (kg)='))
  y=float(input('Tinggi Badan (m)='))

  BMI = x / (y**2)

  return BMI

In [ ]:
bmi()

Berat Badan (kg)=40
Tinggi Badan (m)=155

0.0016649323621227888

4. Update dataframe df dengan menambahkan hasil perhitungan soal nomor 2, beri nama kolom BMI.

In [ ]:
df_15['BMI'] = df_15['Berat Badan (kg)'] / (df_15['Tinggi Badan (m)'] **2)

In [ ]:
df_15

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329
2,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188
5,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308
6,SC61507,Muhammad Durra,Teknik Informatika,60,1.70,20.761246
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915
8,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020
11,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250
15,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726
17,SC61518,Nadira Alivia Mustopo,Ilmu Ekonomi,60,1.70,20.761246
18,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449
19,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453
20,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017

5. Buatlah status BMI untuk setiap siswa dari kategori berikut, lalu simpan data statusnya dengan nama kolom Status BMI.
* Normal: 18.5-24.9
* Overweight: 25.0-29.9
* Obesity: 30.0-34.9
* Underweight: < 18.5

In [ ]:
def status_bmi(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi <= 24.9:
        return 'Normal'
    elif 25.0 <= bmi <= 29.9:
        return 'Overweight'
    elif 30.0 <= bmi <= 34.9:
        return 'Obesity'
    else:
        return 'Invalid'

In [ ]:
df_15['BMI_status'] = df_15['BMI'].apply(status_bmi)

In [ ]:
df_15

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
2,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964,Normal
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188,Normal
5,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308,Normal
6,SC61507,Muhammad Durra,Teknik Informatika,60,1.70,20.761246,Normal
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
8,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722,Normal
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
11,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726,Normal
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
15,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191,Normal
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
17,SC61518,Nadira Alivia Mustopo,Ilmu Ekonomi,60,1.70,20.761246,Normal
18,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449,Normal
19,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal
20,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500,Normal
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal

6. a. Buatlah variabel baru lalu urutkan data berdasarkan tinggi badan dari yang tertinggi ke rendah.




---

In [ ]:
df_15_sorted_tinggi = df_15.sort_values("Tinggi Badan (m)", ascending=False)

In [ ]:
df_15_sorted_tinggi

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
5,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308,Normal
6,SC61507,Muhammad Durra,Teknik Informatika,60,1.70,20.761246,Normal
17,SC61518,Nadira Alivia Mustopo,Ilmu Ekonomi,60,1.70,20.761246,Normal
19,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
20,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500,Normal
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
11,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726,Normal
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
15,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191,Normal
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
8,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722,Normal
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188,Normal
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
18,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449,Normal
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal
2,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964,Normal

6. b. Buat variabel baru lalu urutkan data berdasarkan Nama dari Z – A.

In [ ]:
df_15_sorted_nama = df_15.sort_values("Nama", ascending=False)

In [ ]:
df_15_sorted_nama

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
8,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722,Normal
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
17,SC61518,Nadira Alivia Mustopo,Ilmu Ekonomi,60,1.70,20.761246,Normal
15,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191,Normal
6,SC61507,Muhammad Durra,Teknik Informatika,60,1.70,20.761246,Normal
5,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308,Normal
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188,Normal
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
20,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500,Normal
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
2,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964,Normal
19,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
11,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726,Normal
18,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449,Normal
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal

7. Filter dataframe df berdasarkan:
* Status BMI di luar Normal.

In [ ]:
df_15[df_15['BMI_status'] != 'Normal']

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight

* Tinggi Badan > 169 cm dan Berat Badan > 60 kg

In [ ]:
df_15[(df_15['Tinggi Badan (m)'] > 1.69) & (df_15['Berat Badan (kg)'] > 60)]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
5,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308,Normal
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
19,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal

* Nama yang mengandung huruf “y”.

In [ ]:
df_15[df_15['Nama'].str.contains('y', case=False)]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal
1,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
10,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
14,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal

* Siapa saja yang berat badannya kurang dari 60 kg?

In [ ]:
df_15[df_15['Berat Badan (kg)'] < 60]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
0,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal
2,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964,Normal
3,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
4,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188,Normal
7,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
8,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722,Normal
9,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
11,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726,Normal
12,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
13,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
15,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191,Normal
16,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
18,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449,Normal
21,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
22,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
23,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
24,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal

8. Tambahkan nomor urut pada dataframe df sesuai jumlah siswa dan tempatkan kolom nomor baru tersebut di paling ujung kiri sebagai kolom pertama serta beri nama kolomnya “No.”!

In [ ]:
df_15.insert(0, 'No.', range(1, len(df_15) + 1))

In [ ]:
df_15

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
0,1,SC61501,Aisyah Fitri Kania,Sistem Informasi,54,1.56,22.189349,Normal
1,2,SC61502,Asmal Adyatma Siolimbona,Teknik Informatika,69,1.74,22.790329,Normal
2,3,SC61503,Devia Heraka,Kearsipan,48,1.45,22.829964,Normal
3,4,SC61504,Fauzia Khairunnisa,Matematika,42,1.55,17.481790,Underweight
4,5,SC61505,Indah Kurnia,Teknik Industri,48,1.55,19.979188,Normal
5,6,SC61506,M. Ivan Nuruddin Ishaqi,Matematika,63,1.70,21.799308,Normal
6,7,SC61507,Muhammad Durra,Teknik Informatika,60,1.70,20.761246,Normal
7,8,SC61508,Nasywa Anindya Putri,Psikologi,54,1.59,21.359915,Normal
8,9,SC61509,Qonita Qorirroh,Manajemen,46,1.55,19.146722,Normal
9,10,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal
10,11,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
11,12,SC61512,Angelina,Teknik Informatika,55,1.58,22.031726,Normal
12,13,SC61513,Dhini Nurawiati Purwanda,Sistem Informasi,46,1.60,17.968750,Underweight
13,14,SC61514,Hikmal Aprilian,Statistika,52,1.68,18.424036,Underweight
14,15,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
15,16,SC61516,Muhammad Rizki Taufik,Ekonomi Pembangunan,52,1.57,21.096191,Normal
16,17,SC61517,Radya Ardi Ninang Pudyastuti,Sains Data,55,1.58,22.031726,Normal
17,18,SC61518,Nadira Alivia Mustopo,Ilmu Ekonomi,60,1.70,20.761246,Normal
18,19,SC61519,Amalia Rama Dhani,Teknik Elektro,49,1.52,21.208449,Normal
19,20,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal
20,21,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500,Normal
21,22,SC61522,Luthfia Amanah,Matematika,45,1.57,18.256319,Underweight
22,23,SC61523,Niken Ari Wijayanti,Matematika,58,1.60,22.656250,Normal
23,24,SC61524,Sandy Febrian,Teknik Informatika,52,1.70,17.993080,Underweight
24,25,SC61525,Zafirah Yaffa Zabrina,Akuntansi,52,1.51,22.806017,Normal

9. Cari nilai-nilai berikut:
* Cari nilai terendah dan tertingginya.

In [ ]:
df_15['BMI'].min()

17.48178980228928

In [ ]:
df_15['BMI'].max()

28.906249999999993

* Berapa nilai rata-rata tinggi badan siswa?

In [ ]:
df_15['Tinggi Badan (m)'].mean()

1.6092

* Berapa rata-rata berat badan siswa?

In [ ]:
df_15['Berat Badan (kg)'].mean()

55.68


* Ada berapa orang jumlah siswa  yang tercatat pada dataframe df?

In [ ]:
df_15['Nama'].count()

25

* 5 orang dengan nilai BMI tertinggi.

In [ ]:
df_15.sort_values('BMI', ascending=False).head()

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (m),BMI,BMI_status
14,15,SC61515,Litasya Shofwatillah,Statistika,74,1.60,28.906250,Overweight
19,20,SC61520,Beni Amar,Sistem Informasi Kampus Kota Tegal,70,1.70,24.221453,Normal
20,21,SC61521,Fikri Majid,Teknologi Rekayasa Komputer,60,1.60,23.437500,Normal
10,11,SC61511,Wahyu Dwi Utomo,Sistem Informasi,73,1.78,23.040020,Normal
9,10,SC61510,Sandya Nur Indrawati Karsan,Matematika,55,1.55,22.892820,Normal

* Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [ ]:
sum(df_15['BMI_status'] == 'Underweight')

5

In [ ]:
sum(df_15['BMI_status'] == 'Normal')

19

In [ ]:
sum(df_15['BMI_status'] == 'Overweight')

1

In [ ]:
sum(df_15['BMI_status'] == 'Obesity')

0

**SOAL 2**

Perusahaan Investasi Jamin-Sugih Co kami memberikan penawaran investasi terbaik dengan pembagian keuntungan tetap sebesar 25% setiap tahun.

Buatlah program Python yang dapat menerima input dari pengguna dalam bentuk:
Modal Investasi (bilangan bulat antara 0-1.000.000.000)
Jangka Waktu Investasi (bilangan bulat antara 1-25 dalam tahun)
Selain itu, program akan menampilkan error message bahwa modal atau tenure tidak sesuai ketentuan.

Program akan menampilkan informasi akumulasi investasi setiap tahun, menggunakan iterasi untuk setiap tahun.

In [ ]:
def investasi():
    x=int(input('Money Capital = '))
    y=int(input('Investment Tenure = '))

    if x<0 or x>1000000000:
        print("Your investment is reaching our limit, we can't handle this.")
    elif y<0 or y>25:
        print("Your investment isn't reaching our time limit.")
    else:
        year=0
        total=x
        for z in range(1,(y+1)):
            year=year+1
            total=(total*0.25)+total
            print('Year', year,',', 'Your total investment= ', total)

In [ ]:
investasi()

Money Capital = 500000
Investment Tenure = 10000000
Your investment isn't reaching our time limit.